### PR TITLE
fix: adding error handling and retrying to private chat message retri…

### LINKED ISSUE #315: Fix issue with account_data updates provoking CORS error screen
This is currently happening when starting up the client and many concurrent calls to the account_data PUT endpoint are made. The main flow keeps running towards friend messages fetching when this ends up erring.
Image

### PR DESCRIPTION
**Pull request by moliva**
Fixes #315.

# What? 
...

# Why? 
...

### CODE REVIEW

File: packages/shared/friends/sagas.ts [hunk 1]
```diff
@@ -239,25 +240,60 @@ function* configureMatrixClient(action: SetMatrixClient) {
   yield Promise.all(
```
Comment (menduz) [inline packages/shared/friends/sagas.ts:240]: Maybe wrap this in a try catch to prevent bubbling up the exception to a fatal error
```suggestion
  yield Promise.all(
```

**Review by menduz — APPROVED** [review]
