### PR TITLE
fix: reach pagination limit

### LINKED ISSUE #673: Not all connected members appear in the member list of a channel
Sometimes there is people currently talking in a specific chat channel which is not displayed in the member list.

Repro steps:
1. Join a chat channel through the channel browser
2. Open the member list of the channel
3. Receive message in the channel from different people
4. Sometimes the person is not displayed in the member list, being online at the moment

### PR DESCRIPTION
**Pull request by Julieta11**
Closes #673 

# What? 
When the FF `matrix_presence_disabled` is deactivated, members list pagination does not work as expected, as it first paginates and then checks the presence status of members, leading to possible incorrect pagination.

i.e., the channel has 100 members joined, paging goes from 10 to 10 and we have 5 online members on page 1 and other 4 online members on page 2. We were retrieving only 5 members on the first request when we should be retrieving all 9 online members on the first request.

### CODE REVIEW

File: packages/shared/friends/sagas.ts [hunk 1]
```diff
@@ -1928,36 +1928,37 @@ export async function getChannelMembers(request: GetChannelMembersPayload) {
...
 
-  const ownId = client.getUserId()
-
-  // update catalog with missing users, by using default profiles with name and image url
-  sendMissingProfiles(members, ownId)
-
   // we only notify members who are online if presence is enabled, else every joined member
-  const memberIds = members.map((member) => member.userId)
+  const memberIds = allMembers.map((member) => member.userId)
   const onlineOrJoinedMemberIds = getOnlineOrJoinedMembers(memberIds, client)
```
Comment (Julieta11) [inline packages/shared/friends/sagas.ts:1945]: This is not the best approach especially when there are many members joined, but I thought of it that way because at the moment the explorer team sets the skip value based on how many members they have loaded. We wouldn't be able to know what our last page was, at least we changed the payloads so that we send each other that information. Any thoughts reviewers?
