### PR TITLE
fix: lazy-loading fixes

### LINKED ISSUE #541: Fix lazy-loading related issues
- [X] For `totalFriendsWithDirectMessages` we're sending the same value as the requested one, instead of the actual value of the total friends with DMs.

- [x]  For `totalReceivedFriendRequests` and `totalSentFriendRequests` we're sending the same value as the requested one, instead of the actual value of total requests.

- [x] Pagination does not work in `AddFriendsWithDirectMessages`.

### PR DESCRIPTION
**Pull request by Julieta11**
Closes #541 

# What? 

- [x]  For `totalFriendsWithDirectMessages` we're sending the same value as the requested one, instead of the actual value of the total friends with DMs.

- [x]  For `totalReceivedFriendRequests` and `totalSentFriendRequests` we're sending the same value as the requested one, instead of the actual value of total requests.

- [x] Pagination does not work in `AddFriendsWithDirectMessages`.

### CODE REVIEW

File: packages/shared/friends/sagas.ts [hunk 1]
```diff
@@ -220,8 +220,10 @@ function* configureMatrixClient(action: SetMatrixClient) {
       if (userId) {
         // When it's a friend and is not added to catalog
         // unity needs to know this information to show that the user has connected
-        if (isFriend(store.getState(), userId) && !isAddedToCatalog(store.getState(), userId)) {
+        if (!isAddedToCatalog(store.getState(), userId)) {
           await ensureFriendProfile(userId)
+        }
+        if (isFriend(store.getState(), userId)) {
```
Comment (moliva) [inline packages/shared/friends/sagas.ts:226]: I'm wondering about keeping this block the same as before instead. Two questions related to this:
1- What's the value of sending the profile to renderer if it's not a friend (at least for the logic here)?
2- Is it idempotent for renderer to `AddFriends` a given user id?

File: packages/shared/friends/sagas.ts [hunk 2]
```diff
@@ -762,12 +764,22 @@ function* initializeStatusUpdateInterval() {
...
+    // When it's a friend and is not added to catalog
+    // unity needs to know this information to show that the user has connected
+    friends.forEach(async (friend) => {
+      if (!isAddedToCatalog(store.getState(), friend)) {
+        await ensureFriendProfile(friend)
+      }
+      getUnityInstance().AddFriends({
+        friends: [friend],
+        totalFriends: getTotalFriends(store.getState())
+      })
```
Comment (moliva) [inline packages/shared/friends/sagas.ts:782]: Fine with this, but extract the arrow function into a function to be used here and above (in the previous comment) for ensuring a friend profile is sent to renderer and added as friend as well.

**Review by moliva — COMMENTED** [review]
Leaving some comments.

File: packages/shared/friends/sagas.ts (hunk 2 above)
Comment (Julieta11) [reply packages/shared/friends/sagas.ts]: Comment discarded because I've reverted this change.

File: packages/shared/friends/sagas.ts (hunk 1 above)
Comment (Julieta11) [reply packages/shared/friends/sagas.ts:223]: 1- Yes, you're right. It doesn't have any. So, instead, I changed the code to: 
```
if (isFriend(store.getState(), userId)) {
      if (!isAddedToCatalog(store.getState(), userId)) {
        await ensureFriendProfile(userId)
      }
      getUnityInstance().AddFriends({
        friends: [userId],
        totalFriends: getTotalFriends(store.getState())
      })
}
```
Because there is a scenario where we already sent the profile but not the friendship info.

2- Yes.

Comment (moliva) [reply packages/shared/friends/sagas.ts:223]: Great, thank you!

**Review by menduz — APPROVED** [review]

**Review by guidota — APPROVED** [review]
